jasypt:
  encryptor:
    password: gientech      #密码加密--盐,用JasyptUtil.java加密

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848     #nacos注册中心地址

  datasource:
    url: jdbc:mysql://localhost:3306/crm_testdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    jdbc:mysql://localhost:3306/crm_testdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    CRM_TESTDB  crm_testdb
#    jdbc:mysql://localhost:3306/finalproject?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30                           #默认10，一般为 cpu数*2+磁盘数+10（另外加的10保证服务载的时候连接不会被频繁recycle）
      connection-test-query: select 1 from dual       #mysql配置(select 1), oracle配置(select 1 from dual)

  redis:
    host: localhost
    port: 6379
    password:
    database: 5        #有16个库(索引可选0-15,默认为0)