/**【T_DEMO_SAMPLE】开始**/
drop table if exists T_DEMO_SAMPLE;
CREATE TABLE T_DEMO_SAMPLE
(
	SAMPLE_ID varchar(32) NOT NULL COMMENT '手输主键',
	STRING_TYPE varchar(100) NOT NULL COMMENT '字符型',
	DOUBLE_TYPE double(8,2) NOT NULL COMMENT '浮点型',
	DATE_TYPE date NOT NULL COMMENT '日期型',
	TIME_TYPE datetime NOT NULL COMMENT '时间型',
	INT_TYPE int(4) NOT NULL COMMENT '整数型',
	CODE_TYPE_ID varchar(32) NOT NULL COMMENT '下拉框',
	REMARK varchar(400) NULL COMMENT '备注',
	VER int(5) NOT NULL COMMENT '数据版本',
	PRIMARY KEY (SAMPLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DEMO_01_CRUD示例';
/**【T_DEMO_SAMPLE】结束**/

